#####################################################################
# site reliability engineering | delivery                           #
#   nexus-core | nxc-pipeline v0.1.0                                #
#####################################################################


default:
  image: nexuscore/phase-smith:latest


stages:
  - test
  - build
  - release
  - deploy
  - performance
  - security


# pipeline : build and test

nxc-test:
  stage:  test
  script: servitor test
  only:
    refs:
      - /^issue\/.*/i
      - /^feature\/.*/i
      - /^release\/.*/i
      - /^hotfix\/.*/i
      - develop
      - tags

nxc-build:
  stage:  build
  script: servitor test
  only:
    refs:
      - /^issue\/.*/i
      - /^feature\/.*/i
      - /^release\/.*/i
      - /^hotfix\/.*/i
      - develop


# pipeline :  deployment | development environment

nxc-release-dev:
  stage:  release
  script: servitor release
  environment:
    name: development
  only:
    refs:
      - /^issue\/.*/i
      - /^feature\/.*/i
      - /^hotfix\/.*/i
      - develop
  artifacts:
    paths:
      - release/apps-*.tgz

nxc-deploy-dev:
  stage:  deploy 
  script: servitor deploy
  environment:
    name: development
  only:
    refs:
      - /^issue\/.*/i
      - /^feature\/.*/i
      - /^hotfix\/.*/i
      - develop

